# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Runs a set of commands using the runners shell
    - name: Setup up virtualenv
      run : |
        python3 -m pip install setuptools
        python3 -m pip install virtualenv
        python3 -m virtualenv .venv
        source .venv/bin/activate
    - name: Install test-requirements.
      run: |
        pip3 install cython
        pip3 install --no-binary :all: falcon
        pip3 install jinja2
        python3 -m pip install -r "test-requirements.txt"
    - name: Test
      run: python3 -m pytest tests/
